/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package ZirboinFinancial;

/**
 *
 * @author pehor9164
 */
public class ZirboinFinancial extends javax.swing.JFrame {

    /**
     * Creates new form ZirboinFinancial
     */
    public ZirboinFinancial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        titlelbl = new javax.swing.JLabel();
        promptLbl = new javax.swing.JLabel();
        vorbitsTxtFeild = new javax.swing.JTextField();
        drobzitsLbl = new javax.swing.JLabel();
        calculateBtn = new javax.swing.JButton();
        clickwicksLbl = new javax.swing.JLabel();
        gazoontightsLbl = new javax.swing.JLabel();
        frazointsLbl = new javax.swing.JLabel();
        blointointsLbl = new javax.swing.JLabel();
        vorbitsLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titlelbl.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        titlelbl.setText("ZirboinFinancial");
        jPanel1.add(titlelbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, 270, -1));

        promptLbl.setText("Enter Number Of Vorbits:");
        jPanel1.add(promptLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, -1, -1));
        jPanel1.add(vorbitsTxtFeild, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 120, -1));

        drobzitsLbl.setText("Number of Drobzits: ");
        jPanel1.add(drobzitsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        calculateBtn.setText("Calculate");
        calculateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calculateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(calculateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        clickwicksLbl.setText("Number of Clickwicks:");
        jPanel1.add(clickwicksLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        gazoontightsLbl.setText("Number of Gazoontights: ");
        jPanel1.add(gazoontightsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));

        frazointsLbl.setText("Number of Frazoints:");
        jPanel1.add(frazointsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));

        blointointsLbl.setText("Number of Blointoints:");
        jPanel1.add(blointointsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, -1, -1));

        vorbitsLbl.setText("Number of Vorbits:");
        jPanel1.add(vorbitsLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void calculateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calculateBtnActionPerformed
        //variables
        int vorbits,drobzits,clickwicks,gazoontights,frazoints,blointoints;
        
        try {
        vorbits = Integer.parseInt(vorbitsTxtFeild.getText());
        drobzits = vorbits / 100000;
        vorbits = vorbits % 100000;
        clickwicks = vorbits / 50000;
        vorbits = vorbits % 50000;
        gazoontights = vorbits / 10000;
        vorbits = vorbits % 10000;
        frazoints = vorbits / 1000;
        vorbits = vorbits % 1000;
        blointoints = vorbits / 500;
        vorbits = vorbits % 500;
        
        //Output
        drobzitsLbl.setText("Number of Drobzits: " + drobzits);
        clickwicksLbl.setText("Number of Clickwicks: " + clickwicks);
        gazoontightsLbl.setText("Number of Gazoontights: " +gazoontights);
        frazointsLbl.setText("Number of Frazoints: " + frazoints);
        blointointsLbl.setText("Number of Blointoints: " + blointoints);
        vorbitsLbl.setText("Number of Vorbits: " + vorbits);
        }
        catch (NumberFormatException nfe){
                    System.err.println("You must use Ints");
                    System.err.println("Exception: " + nfe);
                    
                }
    }//GEN-LAST:event_calculateBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ZirboinFinancial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ZirboinFinancial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ZirboinFinancial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ZirboinFinancial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ZirboinFinancial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel blointointsLbl;
    private javax.swing.JButton calculateBtn;
    private javax.swing.JLabel clickwicksLbl;
    private javax.swing.JLabel drobzitsLbl;
    private javax.swing.JLabel frazointsLbl;
    private javax.swing.JLabel gazoontightsLbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel promptLbl;
    private javax.swing.JLabel titlelbl;
    private javax.swing.JLabel vorbitsLbl;
    private javax.swing.JTextField vorbitsTxtFeild;
    // End of variables declaration//GEN-END:variables
}
